//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProV3.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitirmeProjesiDBEntities : DbContext
    {
        public BitirmeProjesiDBEntities()
            : base("name=BitirmeProjesiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_IndexKart> TBL_IndexKart { get; set; }
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_Kullanici> TBL_Kullanici { get; set; }
        public virtual DbSet<TBL_KullaniciOzellik> TBL_KullaniciOzellik { get; set; }
        public virtual DbSet<TBL_Profil> TBL_Profil { get; set; }
        public virtual DbSet<TBL_ProfilIcerik> TBL_ProfilIcerik { get; set; }
        public virtual DbSet<TBL_Yorumlar> TBL_Yorumlar { get; set; }
        public virtual DbSet<TBL_IndexCardComment> TBL_IndexCardComment { get; set; }
        public virtual DbSet<TBL_ProfilKart> TBL_ProfilKart { get; set; }
    }
}
