//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProV3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Yorumlar
    {
        public int YorumID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Yorum { get; set; }
        public string YorumYapanKulAdi { get; set; }
        public string YorumYapanKulPP { get; set; }
        public Nullable<byte> Puan { get; set; }
    
        public virtual TBL_Kullanici TBL_Kullanici { get; set; }
    }
}
