//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProV3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Kullanici()
        {
            this.TBL_IndexKart = new HashSet<TBL_IndexKart>();
            this.TBL_Yorumlar = new HashSet<TBL_Yorumlar>();
        }
    
        public int KullaniciID { get; set; }
        public string Adi { get; set; }
        public string E_posta { get; set; }
        public string Telefon { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<System.DateTime> UyelikTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_IndexKart> TBL_IndexKart { get; set; }
        public virtual TBL_KullaniciOzellik TBL_KullaniciOzellik { get; set; }
        public virtual TBL_Profil TBL_Profil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Yorumlar> TBL_Yorumlar { get; set; }
    }
}
