//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProV3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProfilKart
    {
        public int ProfilKartID { get; set; }
        public string PKart_Baslik { get; set; }
        public string PKart_Aciklama { get; set; }
        public string PKart_Resim { get; set; }
        public Nullable<int> ProfilID { get; set; }
    
        public virtual TBL_Profil TBL_Profil { get; set; }
    }
}
