//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProV3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Profil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Profil()
        {
            this.TBL_ProfilKart = new HashSet<TBL_ProfilKart>();
        }
    
        public int ProfilID { get; set; }
        public Nullable<int> ToplamIsSayisi { get; set; }
        public Nullable<int> OrtalamaYanitSure { get; set; }
        public Nullable<System.DateTime> SonGiris { get; set; }
    
        public virtual TBL_Kullanici TBL_Kullanici { get; set; }
        public virtual TBL_ProfilIcerik TBL_ProfilIcerik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ProfilKart> TBL_ProfilKart { get; set; }
    }
}
